backend:
  name: git-gateway
  accept_roles:
    - admin

media_folder: static/media
public_folder: /media

collections:
  - label: Pages
    name: pages
    files:
      - label: Home
        name: index
        file: src/markdown/index.md
        fields:
          - label: Body
            name: body
            widget: markdown
          - label: Header Image
            name: headerImage
            widget: image
          - label: Header Image Description
            name: headerImageDesc
            widget: string
      - label: Contact
        name: contact
        file: src/markdown/contact.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Privacy Policy
        name: privacy-policy
        file: src/markdown/privacy-policy.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Address
            name: address
            widget: text
          - label: Email
            name: email
            widget: string
          - label: Body
            name: body
            widget: markdown
      - label: Page Not Found
        name: '404'
        file: src/markdown/404.md
        fields:
          - label: Title
            name: title
            widget: string
          - label: Body
            name: body
            widget: markdown
  - label: Products
    name: products
    folder: src/markdown/products
    create: true
    fields:
      - label: Name
        name: title
        widget: string
      - label: ID
        name: id
        widget: string
        pattern:
          - ^[a-zA-Z0-9_-]+$
          - Must contain only alphanumeric characters and hyphens
        hint: Must contain only alphanumeric characters and hyphens
      - label: Category
        name: category
        widget: relation
        collection: categories
        searchFields:
          - id
          - title
        valueField: id
        displayFields:
          - title
      - label: Color
        name: color
        widget: string
      - label: Price
        name: price
        widget: currency
        required: false
        default: 0
      - label: Body
        name: body
        widget: markdown
      - label: Order
        name: order
        widget: number
        valueType: int
        default: 1
        hint: Products on the site are ordered from lowest to highest number
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: Variants
        name: variants
        widget: list
        required: false
        fields:
          - label: Color
            name: color
            widget: string
          - label: ID
            name: id
            widget: string
            pattern:
              - ^[a-zA-Z0-9_-]+$
              - Must contain only alphanumeric characters and hyphens
  - label: Categories
    name: categories
    folder: src/markdown/categories
    create: true
    fields:
      - label: Name
        name: title
        widget: string
      - label: Path
        name: id
        widget: string
        pattern:
          - ^[a-zA-Z0-9_-]+$
          - Must contain only alphanumeric characters and hyphens
      - label: Body
        name: body
        widget: markdown
      - label: Published
        name: published
        widget: boolean
        default: true
  - label: Blog
    name: blog
    folder: src/markdown/blog
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Tags
        name: tags
        widget: list
      - label: Path
        name: path
        widget: string
        pattern:
          - ^[a-z0-9_-]+$
          - Must contain only lowercase characters and hyphens
        hint: The URL to the page. Must contain only lowercase characters and hyphens
        required: false
      - label: Image
        name: image
        widget: image
        required: false
      - label: Image Description
        name: imageDesc
        widget: string
        required: false
      - label: Body
        name: body
        widget: markdown
      - label: Published
        name: published
        widget: boolean
        default: true
  - label: Approved Comments
    name: approved-comments
    folder: src/markdown/comments
    filter:
      field: published
      value: true
    create: false
    fields:
      - label: Date
        name: date
        widget: date
      - label: Name
        name: title
        widget: string
      - label: Email
        name: email
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Slug
        name: slug
        widget: hidden
      - label: MD5
        name: md5
        widget: hidden
      - label: Approved
        name: published
        widget: boolean
        default: false
  - label: Unapproved Comments
    name: unapproved-comments
    folder: src/markdown/comments
    filter:
      field: published
      value: false
    create: false
    fields:
      - label: Date
        name: date
        widget: date
      - label: Name
        name: title
        widget: string
      - label: Email
        name: email
        widget: string
      - label: Body
        name: body
        widget: markdown
      - label: Slug
        name: slug
        widget: hidden
      - label: MD5
        name: md5
        widget: hidden
      - label: Approved
        name: published
        widget: boolean
        default: false
  - label: Settings
    name: settings
    files:
      - label: Site Settings
        name: site
        file: src/markdown/site.md
        fields:
          - label: Title
            name: title
            widget: hidden
            default: Site Settings
          - label: Site Title
            name: siteTitle
            widget: text
          - label: Site Description
            name: siteDescription
            widget: text
          - label: Maximum Posts Per Page
            name: postsPerPage
            widget: number
            valueType: int
            min: 1